--- #YAML:1.0
name:               ConfigReader-Simple
version:            1.28
abstract:           Simple configuration file parser
author:
    - brian d foy <bdfoy@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:          5.006
    Test::Output:  0
    Test::Warn:    0
resources:
    repository:  git://github.com/briandfoy/test-output.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:
    - testing
    - STDOUT
    - STDERR
